update search, snoop and ui versions

diff --git a/ci/tests/1-hoover b/ci/tests/1-hoover
--- a/ci/tests/1-hoover
+++ b/ci/tests/1-hoover
@@ -28,14 +28,14 @@ set +x
 echo "Waiting for processing to finish..."
 wait_testdata
 
-echo "Retrying errors 2 times..."
-timeout 100 ./liquid dockerexec hoover:snoop ./manage.py retrytasks testdata --status error || true
-timeout 100 ./liquid dockerexec hoover:snoop ./manage.py retrytasks testdata --status broken || true
-wait_testdata
-
-timeout 100 ./liquid dockerexec hoover:snoop ./manage.py retrytasks testdata --status error || true
-timeout 100 ./liquid dockerexec hoover:snoop ./manage.py retrytasks testdata --status broken || true
-wait_testdata
+# echo "Retrying errors 2 times..."
+# timeout 100 ./liquid dockerexec hoover:snoop ./manage.py retrytasks testdata --status error || true
+# timeout 100 ./liquid dockerexec hoover:snoop ./manage.py retrytasks testdata --status broken || true
+# wait_testdata
+# 
+# timeout 100 ./liquid dockerexec hoover:snoop ./manage.py retrytasks testdata --status error || true
+# timeout 100 ./liquid dockerexec hoover:snoop ./manage.py retrytasks testdata --status broken || true
+# wait_testdata
 
 echo "Documents processed."
 
