Deployment improvements (#354)
* nomad: print container error logs on deployment

* deploy script: don't wait for stopping if checks=false

* rocketchat: fix mongodb config for new servers

* ci: fix config names

* change all bash scripts to use 'set -ex'

* ci: set secret file readable by repo

* allow first retry to print to stderr

* fix backup/restore caused by bad stdout/err pipe [ci skip]

* deploy: print nomad URL with logs

* send healthcheck name list to liquid-core

* deployment: healthcheck status page in homepage

* update prod versions: search, snoop, core

diff --git a/ci/tests/3-integration b/ci/tests/3-integration
--- a/ci/tests/3-integration
+++ b/ci/tests/3-integration
@@ -1,4 +1,5 @@
-#!/bin/bash -ex
+#!/bin/bash
+set -ex
 
 #cd /opt/node
 cd "$(dirname ${BASH_SOURCE[0]})/../.."
@@ -8,4 +9,4 @@ cp ci/conf/1-with-collections.ini liquid.ini
 
 set -x
 echo "Run UI test suite... (2nd pass)"
-(cd ./ci/ui/ && ./run_ui_tests.sh) || (echo "!!!\nUI TESTS FAILED! SLEEPING 30min\n!!!!" && sleep 1800 && exit 1) || true
+(cd ./ci/ui/ && ./run_ui_tests.sh) || (echo "!!!\nUI TESTS FAILED!" && exit 1) || true
